spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: ${SERVER_PORT}
